//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestG.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietSuaChua
    {
        public int IDSuaChu { get; set; }
        public Nullable<int> IDVatTu { get; set; }
        public Nullable<int> IDMaSuaChu { get; set; }
        public string NoiDung { get; set; }
        public Nullable<int> DonGia { get; set; }
        public Nullable<int> SoLuongVatTu { get; set; }
        public Nullable<int> TongTien { get; set; }
        public Nullable<int> IDTienCong { get; set; }
        public Nullable<int> IDNhanCong { get; set; }
        public Nullable<int> IDKiemTra { get; set; }
    }
}
