//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestG.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CTTonKho
    {
        public int IDVatTu { get; set; }
        public int IDTonKho { get; set; }
        public Nullable<int> TonDau { get; set; }
        public Nullable<int> PhatSinh { get; set; }
        public Nullable<int> TonCuoi { get; set; }
    
        public virtual TonKho TonKho { get; set; }
        public virtual VatTu VatTu { get; set; }
    }
}
